### ISSUE TITLE
404 error on font file

### ISSUE THREAD

**Issue by fasterwp** [richtabor/wabi#1]
Hi,

I get a 404 error in the browser console for wp-content/themes/wabi/assets/fonts/Inter-Roman.var.woff2.
However the font seems to work, the wp-content/themes/wabi/assets/fonts/inter-roman.woff2 font file is loaded. 
The website is andreichira.ro.

**Comment by richtabor** [comment]
Hey @fasterwp — appreciate the report. I just merged a fix. I have one more thing I want to push, then I'll cut a release.
