### ISSUE TITLE
header-w-button pattern: navigation block attributes - unwanted } for layout 

### ISSUE THREAD

**Issue by bobbingwide** [richtabor/wabi#11]
There is an unwanted closing curly brace ( `}` ) in the header-w-button pattern.
It's in/after the `layout` attribute for the `navigation` block
This caused a Fatal error in my development environment when viewing the patterns for the theme.
Removing the `}` resolves the issue.  

This is the non working version, slightly reformatted

```
<!-- wp:navigation {
"overlayTextColor":"foreground",
"overlayBackgroundColor":"background",
"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"}},
"style":{"spacing":{"blockGap":"1.5rem"}}
} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->
``` 

See https://github.com/bobbingwide/bobbingwide/issues/58

**Comment by bobbingwide** [comment]
PS. I've resolved the issue for the live site. See https://blocks.wp-a2z.org/oik-themes/wabi/?oik-tab=patterns

**Comment by richtabor** [comment]
Thanks for the catch @bobbingwide — I've closed it with https://github.com/richtabor/wabi/commit/cf595dec6bd7b171789eec4a0016f3997652232d
