### ISSUE TITLE
Accent colors preview missing in settings

### ISSUE THREAD

**Issue by peiche** [richtabor/wabi#15]
In the most recent version of Gutenberg (13.2.2 as of this writing), the accent colors are not showing up in the settings sidebar. Note that this affects neither the accent color shown in the editor's title, nor the header in the rendered post.

I have attached a screenshot as an example.

![image](https://user-images.githubusercontent.com/613931/169826056-dc664384-2206-4bb6-9337-f52535239748.png)

**Comment by richtabor** [comment]
Interesting 🤔 — I'll take a look :)

**Comment by richtabor** [comment]
Closed in https://github.com/richtabor/wabi/commit/c91a180fba58c10610c3e7bbc89186a4fda99bfd — I'll cut a release shortly.
