### ISSUE TITLE
Cannot change Social Media icons in Header

### ISSUE THREAD

**Issue by tibesararchives** [richtabor/wabi#17]
Hi Rich, 

I am unable to change the social media icons in Wabi's header (Twitter/WordPress/Github).

I can change the URL link but nothing else.

Have you locked this template part? Am I missing something?

Thank you for a wonderful FSE theme!

Marcus Tibesar
marcustibesar.com

**Comment by richtabor** [comment]
Hey Marcus, sorry I missed this 😬

There are two templates used for the theme; the header and header-accent (for the single post view). You'll need to update both of those. 

I did that so the header could adopt the background accent color of the single post.
