### ISSUE TITLE
Missing vertical space above tables

### ISSUE THREAD

**Issue by erikjoling** [richtabor/wabi#6]
On the frontend the vertical space above tables is missing (post-content). In the editor this spacing is present. 

![image](https://user-images.githubusercontent.com/20614110/155529600-49492fcc-7c9d-4c08-893f-aef94bfcbed2.png)

**Comment by richtabor** [comment]
Hmm, can you paste the block code in here, or make a gist, so I can see it first hand — here's what I'm seeing: 
<img width="739" alt="CleanShot 2022-02-24 at 09 27 48@2x" src="https://user-images.githubusercontent.com/1813435/155543271-1d0f4d94-289f-4485-8328-e228c6e93f51.png">

**Comment by erikjoling** [comment]
Yeah sure;

```
[...]
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table><tbody><tr><td>Test</td><td>Test</td></tr><tr><td>Test</td><td>Test</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph -->
[...]
```
I'm using WordPress 5.9.1 without the Gutenberg plugin

**Comment by richtabor** [comment]
Is this still an issue with 6.0? Thanks.

**Comment by erikjoling** [comment]
> Is this still an issue with 6.0? Thanks.

Thanks for the heads-up. Just tested it and it seems to work fine now :)
